description: >
  CircleCI's Node convenience image:
  https://hub.docker.com/r/cimg/node

parameters:
  tag:
    type: string
    default: "13.11"
    description: >
      Pick a specific cimg/node image version tag:
      https://hub.docker.com/r/cimg/node

docker:
  - image: cimg/node:<<parameters.tag>>
