#!/bin/bash

set -e -o pipefail

if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

# FUNCTIONS
get_npm_NPM_VERSION () {
  if [[ $NPM_VERSION == latest ]]; then
    NPM_ORB_VERSION="$(npm view npm | sed -E 's|.*-||g' | grep latest | \
      perl -pe 's/.*: //g' | perl -pe "s/'|,//g")"

    echo "Latest NPM_VERSION of NPM is $NPM_ORB_VERSION"
  else
    NPM_ORB_VERSION=$NPM_VERSION

    echo "Selected NPM_VERSION of NPM is $NPM_ORB_VERSION"
  fi
}

installation_check () {
  if command -v npm > /dev/null 2>&1; then
    if npm -v | grep "$NPM_ORB_VERSION" > /dev/null 2>&1; then
      echo "NPM $NPM_ORB_VERSION is already installed"
      exit 0
    fi
  fi
}

get_npm_NPM_VERSION
  installation_check

  if [[ "${NPM_VERSION}" == latest ]]; then
    $SUDO npm install -g npm@latest > /dev/null 2>&1 || \
      npm install -g npm@latest > /dev/null 2>&1
  else
    $SUDO npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1 || \
      npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1
  fi

  # test/verify NPM_VERSION
  if npm -v | grep "$NPM_ORB_VERSION" > /dev/null 2>&1; then
    echo "Success! NPM $(npm -v) has been installed to $(which npm)"
  else
    echo "Something went wrong; the specified NPM_VERSION of NPM could not be installed"
    exit 1
  fi
